openapi: 3.0.0
info:
  version: 0.1.0-alpha
  title: short API
  contact:
    email: info@oppie.io
  x-logo:
    url: 'assets/img/oppie-logo.png'
    href: 'https://short.oppie.io'
  description: >
    Domain-specific content summarization.

    # Overview

    Integrate in a snap with a **production-grade** content summarizer.


    Powered by machine learning, **short** implements a model trained via [unsupervised learning using sentence embeddings](https://www.cs.utexas.edu/~asaran/reports/summarization.pdf) and tailored for particular use cases.

    ## Release Warning*

    The following documentation and subsequent API is __subject to change__ as the service is currently in an `alpha` state.

    ## API Host

    All requests are made to the following root URL with the `/api` prefix.


    `https://short.oppie.io/api`
    
externalDocs:
  description: short.oppie.io
  url: 'https://short.oppie.io'
tags:
  - name: Condense Content
    description: Operations for condensing content using the **short** machine learning model.
servers:
  - url: 'https://short.oppie.io/api'
security:
  - ApiKeyAuth: []
